### ISSUE TITLE
Redmi more visualizations.

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [wpbones/WPKirk#13]
It's good to add more images of how it looks for better understanding.

Example: https://github.com/LaravelDaily/FilaStart

**Comment by gfazioli** [comment]
@YevheniiVolosiuk you can see the plugin demo in cation [here](https://playground.wordpress.net/?blueprint-url=https://wpbones.vercel.app/blueprint.json)
and check the completed docs [here](https://wpbones.vercel.app/docs)
