### ISSUE TITLE
Trouble with PHP Bones command

### ISSUE THREAD

**Issue by mrcrandell** [wpbones/WPKirk#3]
When I attempt to run the php bones command, it simply thinks for a bit then just goes to the next time without any output. I've also tried the install command as well.

I am running PHP 7.1.10.

**Comment by gfazioli** [comment]
Hi, `php bones` must be run on the host machine, with WordPress up & running. Could you check again?

**Comment by mrcrandell** [comment]
I am running Valet locally on my machine. Is there something more than just navigating to the new directory in Terminal?

**Comment by gfazioli** [comment]
@mrcrandell I'm using *valet* as well. Could you provide me with the complete folder where you are running the `php bones` command? I mean, for example, you should be in `/wp-content/plugins/WPKirk`

**Comment by mrcrandell** [comment]
@gfazioli Thank you for following up.
Here is the complete folder: /Users/mrcrandell/Documents/Crandell Design Drive/Crandell Design Websites/Crandell Hosting/html/habitatoakland/wp-content/plugins/form-to-database-demo

"habitatoakland" is the wordpress install linked with Laravel Valet.

**Comment by gfazioli** [comment]
@mrcrandell very strange, the path seems ok... please, try with `php bones update`

**Comment by mrcrandell** [comment]
Below is all that is happening when I attempt `php bones update` along with a few other attempts:
![screen shot 2018-03-13 at 6 05 27 pm](https://user-images.githubusercontent.com/4225417/37372454-2f0d52c2-26e9-11e8-84cf-9fcfd9b882d5.png)

For more information, here is my php path: /usr/local/php5-7.1.10-20171002-090111/bin/php

**Comment by gfazioli** [comment]
do you have any chance to get any logs from there?

**Comment by gfazioli** [comment]
maybe I was able to replicate the issue, please try:

```sh
$ composer dump-autoload -o
```

if it not working yet, try:

```sh
$ rm -ef vendor
$ composer update --no-scripts
$ composer dump-autoload -o
```

**Comment by mrcrandell** [comment]
Before trying your solution, my log displays:
`[14-Mar-2018
 10:41:06 UTC] PHP Fatal error:  Uncaught Error: Class 'WPKirk\WPBones\Foundation\Plugin' not found in /Users/mrcrandell/Documents/Crandell Design Drive/Crandell Design Websites/Crandell Hosting/html/habitatoakland/wp-content/plugins/form-to-database-demo/bootstrap/plugin.php:13
Stack trace:
#0 /Users/mrcrandell/Documents/Crandell Design Drive/Crandell Design Websites/Crandell Hosting/html/habitatoakland/wp-content/plugins/form-to-database-demo/bones(55): require_once()
#1 {main}
  thrown in /Users/mrcrandell/Documents/Crandell Design Drive/Crandell Design Websites/Crandell Hosting/html/habitatoakland/wp-content/plugins/form-to-database-demo/bootstrap/plugin.php on line 13`

Fortunately, running `composer update --no-scripts` and `composer dump-autoload -o` seemed to work and now the `php bones` commands are working.

Thank you so much for your help. I look forward to diving into this.

**Comment by gfazioli** [comment]
@mrcrandell happy to hear that! Have a fun!
